# uptime-kuma-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uptime-kuma-volume
  namespace: uptime
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi